"""Generate a Mermaid ER diagram from SQLAlchemy models."""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from app.models.models import Base
from eralchemy2 import render_er

OUTPUT = Path(__file__).parent.parent.parent / "docs-site" / "src" / "lib" / "erd.ts"


def fix_cardinality(diagram: str) -> str:
    """eralchemy2 occasionally emits English cardinality phrases instead of
    Mermaid crow's-foot syntax. Normalize those to `}o--o{`."""
    # Map common bad phrases to valid mermaid
    replacements = {
        r"one or zero--0\+": "}o--o{",
        r"1--0\+": "||--o{",
        r"1--1\+": "||--|{",
    }
    for pattern, replacement in replacements.items():
        diagram = re.sub(pattern, replacement, diagram)
    return diagram


def extract_mermaid_syntax(raw: str) -> str:
    """eralchemy2's mermaid_er mode wraps the diagram in a markdown comment
    block and appends a mermaid.ink image. Strip both down to the raw syntax."""
    match = re.search(r"<!--\s*\n(.*?)\n-->", raw, re.DOTALL)
    if not match:
        raise ValueError("Could not locate diagram inside eralchemy2 output")
    return match.group(1).strip()


def main():
    mermaid_path = Path("/tmp/erd.mmd")
    render_er(Base, str(mermaid_path), mode="mermaid_er")

    diagram = fix_cardinality(extract_mermaid_syntax(mermaid_path.read_text()))

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "// Auto-generated by backend/scripts/generate_erd.py\n"
        "// Do not edit manually.\n\n"
        f"export const ERD_DIAGRAM = `{diagram}`;\n"
    )
    print(f"Wrote ERD to {OUTPUT} ({len(diagram.splitlines())} lines)")


if __name__ == "__main__":
    main()
