// Auto-generated by backend/scripts/generate_erd.py
// Do not edit manually.

export const ERD_DIAGRAM = `erDiagram
cards {
 VARCHAR id PK
   INTEGER cmc 
   VARCHAR collector_number 
   ARRAY color_identity 
   JSONB image_uris 
   JSONB legalities 
   VARCHAR mana_cost 
   VARCHAR name 
   TEXT oracle_text 
   INTEGER price_eur 
   INTEGER price_usd 
   INTEGER price_usd_foil 
   VARCHAR rarity 
   JSONB scryfall_data 
   VARCHAR set_code 
   VARCHAR set_name 
   VARCHAR type_line 
   DATETIME updated_at 
}
collection {
 VARCHAR id PK
   DATETIME acquired_at 
   VARCHAR condition 
   BOOLEAN foil 
   VARCHAR language 
   TEXT notes 
   INTEGER purchase_price_cents 
   INTEGER quantity 
   VARCHAR scryfall_id 
}
decks {
 VARCHAR id PK
   VARCHAR commander_id 
   DATETIME created_at 
   TEXT description 
   VARCHAR format 
   VARCHAR name 
   DATETIME updated_at 
}
deck_cards {
 VARCHAR id PK
   VARCHAR board 
   ARRAY categories 
   VARCHAR deck_id 
   BOOLEAN foil 
   INTEGER quantity 
   VARCHAR scryfall_id 
}
price_history {
 VARCHAR id PK
   INTEGER price_eur 
   INTEGER price_usd 
   INTEGER price_usd_foil 
   DATETIME recorded_at 
   VARCHAR scryfall_id 
   DATE snapshot_date 
}
edhrec_cache {
 VARCHAR id PK
   DATETIME created_at 
   JSONB data 
   DATETIME expires_at 
   VARCHAR slug 
}
cards ||--o{ collection : has
cards }o--o{ decks : has
cards ||--o{ deck_cards : has
decks ||--o{ deck_cards : has
cards ||--o{ price_history : has`;
