"""initial schema

Revision ID: f47b1ca78159
Revises: 
Create Date: 2026-04-23 04:36:36.822858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f47b1ca78159'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('set_code', sa.String(), nullable=False),
    sa.Column('set_name', sa.String(), nullable=False),
    sa.Column('collector_number', sa.String(), nullable=False),
    sa.Column('mana_cost', sa.String(), nullable=True),
    sa.Column('cmc', sa.Integer(), nullable=False),
    sa.Column('type_line', sa.String(), nullable=False),
    sa.Column('oracle_text', sa.Text(), nullable=True),
    sa.Column('color_identity', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('rarity', sa.String(), nullable=False),
    sa.Column('price_usd', sa.Integer(), nullable=True),
    sa.Column('price_usd_foil', sa.Integer(), nullable=True),
    sa.Column('price_eur', sa.Integer(), nullable=True),
    sa.Column('image_uris', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('legalities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scryfall_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.create_table('edhrec_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edhrec_cache_slug'), 'edhrec_cache', ['slug'], unique=True)
    op.create_table('collection',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scryfall_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('foil', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('purchase_price_cents', sa.Integer(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scryfall_id'], ['cards.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_scryfall_id'), 'collection', ['scryfall_id'], unique=False)
    op.create_table('decks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('commander_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commander_id'], ['cards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scryfall_id', sa.String(), nullable=False),
    sa.Column('price_usd', sa.Integer(), nullable=True),
    sa.Column('price_usd_foil', sa.Integer(), nullable=True),
    sa.Column('price_eur', sa.Integer(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scryfall_id'], ['cards.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_scryfall_id'), 'price_history', ['scryfall_id'], unique=False)
    op.create_table('deck_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deck_id', sa.String(), nullable=False),
    sa.Column('scryfall_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('board', sa.String(), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('foil', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scryfall_id'], ['cards.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_cards_deck_id'), 'deck_cards', ['deck_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deck_cards_deck_id'), table_name='deck_cards')
    op.drop_table('deck_cards')
    op.drop_index(op.f('ix_price_history_scryfall_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('decks')
    op.drop_index(op.f('ix_collection_scryfall_id'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_edhrec_cache_slug'), table_name='edhrec_cache')
    op.drop_table('edhrec_cache')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
